"""test

Revision ID: 445b448b69d2
Revises: 
Create Date: 2022-07-31 21:48:31.497158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445b448b69d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_read', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_read')
    # ### end Alembic commands ###
